language: java
jdk: openjdk8
install: true

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage : build
      script: ./mvnw clean install
      after_success:
        - test $TRAVIS_PULL_REQUEST = false && ./mvnw pact:publish

branches:
  only:
    - master
